# Generated by Django 4.0.3 on 2024-03-07 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('option1', models.CharField(max_length=255, verbose_name='Option1')),
                ('option2', models.CharField(max_length=255, verbose_name='Option2')),
                ('option3', models.CharField(max_length=255, verbose_name='Option3')),
                ('option4', models.CharField(max_length=255, verbose_name='Option4')),
                ('answer', models.CharField(max_length=255, verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email_id', models.EmailField(max_length=255, verbose_name='Email Id')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('country', models.CharField(default='India', max_length=100, verbose_name='Country')),
                ('state', models.CharField(default='Tamil Nadu', max_length=100, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('quiz_id', models.CharField(max_length=100, null=True, unique=True, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.IntegerField(null=True)),
                ('rand_num', models.CharField(max_length=255)),
                ('ans', models.CharField(max_length=255, verbose_name='Answer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdetail')),
            ],
        ),
    ]
