# Generated by Django 3.2 on 2024-04-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
    ]
